# Generated by Django 2.1 on 2018-11-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='est',
            old_name='descr',
            new_name='desc',
        ),
    ]
